package types

// ExecutePayload is the incoming request payload when a copy
// operation is being executed.
type ExecutePayload struct {
	DestinationName string `json:"destination_name"`
	EntryName       string `json:"entry_name"`
	SourceName      string `json:"source_name"`
}

// ExecuteResult is the output generated by a copy request.
type ExecuteResult struct {
	Error      error       `json:"error"`
	References []Reference `json:"references"`
}

// RemovePayload is the incoming payload for a file removal request.
type RemovePayload struct {
	DestinationName string `json:"destination_name"`
	EntryName       string `json:"entry_name"`
}
