name: release build

on:
  push:
    tags:
      - '*'

jobs:

  build:
    strategy:
      matrix:
        os: ['linux', 'darwin', 'windows']
    runs-on: ubuntu-latest
    name: 'Build All Artefacts'
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v4
      - name: 'Setup Go'
        uses: actions/setup-go@v4
        with:
          go-version: ^1.22
      - name: 'Setup Node'
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: 'Build Frontend Artefacts'
        run: yarn && NODE_OPTIONS=--openssl-legacy-provider yarn build
      - name: 'Mirror Dist'
        run: cp -r ./dist ./pkg/server/dist
      - name: 'Compile Binary'
        run: GOOS=${{ matrix.os }} GOARCH=amd64 go build -o dist/roadie-${{ matrix.os }}-amd64 ./cmd/roadie
      - name: 'Archive Binary'
        uses: actions/upload-artifact@v4
        with:
          name: binary-amd64-${{ matrix.os }}
          path: dist/roadie-${{ matrix.os }}-amd64

  release:
    name: 'Create Github Release'
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: ncipollo/release-action@v1
        with:
          artifacts: 'dist/*'

